### ISSUE TITLE
Older child specific danger signs are appearing for YI

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#131] opened 2023-03-29 11:38 UTC

**Comment by delcroip** [comment] 2023-03-29 15:31
Danger sign should only be triggered for > 2 m @kaledip  please confirm

**Comment by kaledip** [comment] 2023-03-30 05:12
> Danger sign should only be triggered for > 2 m @kaledip please confirm

"Convulsing Now'" is a danger sign that is applicable for both age groups. But the rest are only for older child.

**Comment by delcroip** [comment] 2023-04-24 15:47
duplicate of #70

**Closed** 2023-04-24 15:47 UTC
Labels: duplicate, L3, L4

**Comment by kaledip** [comment] 2023-04-25 05:18
Not yet working.
