### ISSUE TITLE
Visually assess for whether underweight (for drug dose calculation) not appearing in measurements

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#170] opened 2023-05-11 11:51 UTC
MUAC is left null or not answered. then we should get the question of 
Visually assess for whether underweight (for drug dose calculation)..

But the question does not appear.

**Comment by kaledip** [comment] 2023-05-16 16:42
Que not appearing yet. Build 681

![Image](https://github.com/WorldHealthOrganization/smart-emcare/assets/122801361/3a2a6575-dd06-4e89-80b8-ca644b6d2bbb)

**Comment by delcroip** [comment] 2023-05-22 13:39
wrong enableWhenExpression , int was check against quantity

**Comment by delcroip** [comment] 2023-05-23 07:14
diplayed is "MUAC cannot ... " checked

**Comment by kaledip** [comment] 2023-05-23 08:03
The question is appearing but not able to submit and proceed to Symptoms stage.


![Image](https://github.com/WorldHealthOrganization/smart-emcare/assets/122801361/cb93fd2f-a6aa-40d2-ba6d-ba078d657ece)

**Comment by delcroip** [comment] 2023-05-23 08:26
Did you select a choice ?

**Comment by delcroip** [comment] 2023-05-24 12:05
the new issue is a duplicate of #180 so please @kaledip  close this one

**Closed** 2023-06-06 07:24 UTC
Labels: duplicate, L3
