### ISSUE TITLE
Classification with 2 qualifiers not showing correctly

### ISSUE THREAD

**Issue by kaledip** [WorldHealthOrganization/smart-emcare#13] opened 2023-01-31 06:52 UTC
Identify "Classification" = "EmCare.B23.DE10 -Cough or Cold"
"Classification - Qualifier" = "EmCare.B23.DE12 - with cough or difficulty breathing  for 14 days or more or recurrent wheeze"
"Classification - Qualifier" = "EmCare.B23.DE11 - with wheezing"

This had 1 main classification and 2 qualifiers but app only shows with wheezing.
Tested for Patient 65.

**Comment by delcroip** [comment] 2023-01-31 08:16
Duplicate of #7

**Closed by delcroip** 2023-01-31 08:16 UTC
